name: kangaroo_app_sdk_macos
description: Kangaroo App SDK Flutter plugin macOS module.
version: 0.0.1
homepage: https://kangaroorewards.com/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  kangaroo_app_sdk_platform_interface:
    path: ../kangaroo_app_sdk_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: KangarooAppSDKMacOSFlutterPlugin
