name: kangaroo_app_sdk
description: A new flutter plugin project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  kangaroo_app_sdk_platform_interface:
#    git:
#      url: https://paulkangaroorewards@bitbucket.org/kangaroorewards/app-sdk-flutter-plugin.git
#      path: kangaroo_app_sdk_platform_interface
#      ref: members_app_dev
    path: ../kangaroo_app_sdk_platform_interface
  kangaroo_app_sdk_android:
#    git:
#      url: https://paulkangaroorewards@bitbucket.org/kangaroorewards/app-sdk-flutter-plugin.git
#      path: kangaroo_app_sdk_android
#      ref: members_app_dev
    path: ../kangaroo_app_sdk_android
  kangaroo_app_sdk_ios:
#    git:
#      url: https://paulkangaroorewards@bitbucket.org/kangaroorewards/app-sdk-flutter-plugin.git
#      path: kangaroo_app_sdk_ios
#      ref: members_app_dev
    path: ../kangaroo_app_sdk_ios
#  kangaroo_app_sdk_macos:
#    #    git:
#    #      url: https://paulkangaroorewards@bitbucket.org/kangaroorewards/app-sdk-flutter-plugin.git
#    #      path: kangaroo_app_sdk_ios
#    #      ref: members_app_dev
#    path: ../kangaroo_app_sdk_macos
  kangaroo_app_sdk_web:
#    git:
#      url: https://paulkangaroorewards@bitbucket.org/kangaroorewards/app-sdk-flutter-plugin.git
#      path: kangaroo_app_sdk_web
#      ref: members_app_dev
    path: ../kangaroo_app_sdk_web

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        default_package: kangaroo_app_sdk_android
      ios:
        default_package: kangaroo_app_sdk_ios
      web:
        default_package: kangaroo_app_sdk_web