name: kangaroo_app_sdk_platform_interface
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  plugin_platform_interface: ^2.0.2
  freezed: ^0.15.0+1
  json_annotation: ^4.3.0
  built_value: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  build_runner: ^2.1.4
  json_serializable: ^6.0.1

flutter: